{
  "data": [
    {
      "COD_SEDE": "15",
      "NOM_SEDE": "LIMA",
      "NOM_USUARIO": "COAQUIRA PINEDA, SILVIA",
      "CARGO": "ENCUESTADORA",
      "PERIODO": "1",
      "DISTRITO": "SAN SEBASTIAN",
      "NOMCCPP": "SAN SEBASTIAN",
      "CUESTIONARIO": "1",
      "CONG_T": "376660",
      "VIV": "1",
      "ACTIVIDAD": "Recuperar",
      "FECHA": "3-Ago",
      "HORAVISITA": "8:00",
      "HORADECITA": "",
      "OBSERVACIONES": "",
      "FECHA_CREACION": "23/07/2021"
    },
    {
      "COD_SEDE": "15",
      "NOM_SEDE": "LIMA",
      "NOM_USUARIO": "COAQUIRA PINEDA, SILVIA",
      "CARGO": "ENCUESTADORA",
      "PERIODO": "1",
      "DISTRITO": "SAN SEBASTIAN",
      "NOMCCPP": "SAN SEBASTIAN",
      "CUESTIONARIO": "1",
      "CONG_T": "376660",
      "VIV": "2",
      "ACTIVIDAD": "Encuestar",
      "FECHA": "3-Ago",
      "HORAVISITA": "9:00",
      "HORADECITA": "",
      "OBSERVACIONES": "",
      "FECHA_CREACION": "23/07/2021"
    },
    {
      "COD_SEDE": "15",
      "NOM_SEDE": "LIMA",
      "NOM_USUARIO": "COAQUIRA PINEDA, SILVIA",
      "CARGO": "ENCUESTADORA",
      "PERIODO": "1",
      "DISTRITO": "SAN SEBASTIAN",
      "NOMCCPP": "SAN SEBASTIAN",
      "CUESTIONARIO": "1",
      "CONG_T": "376660",
      "VIV": "3",
      "ACTIVIDAD": "Encuestar",
      "FECHA": "3-Ago",
      "HORAVISITA": "10:00",
      "HORADECITA": "",
      "OBSERVACIONES": "",
      "FECHA_CREACION": "23/07/2021"
    },
    {
      "COD_SEDE": "15",
      "NOM_SEDE": "LIMA",
      "NOM_USUARIO": "COAQUIRA PINEDA, SILVIA",
      "CARGO": "ENCUESTADORA",
      "PERIODO": "1",
      "DISTRITO": "SAN SEBASTIAN",
      "NOMCCPP": "SAN SEBASTIAN",
      "CUESTIONARIO": "1",
      "CONG_T": "376660",
      "VIV": "4",
      "ACTIVIDAD": "Supervisar",
      "FECHA": "3-Ago",
      "HORAVISITA": "11:00",
      "HORADECITA": "",
      "OBSERVACIONES": "",
      "FECHA_CREACION": "23/07/2021"
    },
    {
      "COD_SEDE": "15",
      "NOM_SEDE": "LIMA",
      "NOM_USUARIO": "COAQUIRA PINEDA, SILVIA",
      "CARGO": "ENCUESTADORA",
      "PERIODO": "1",
      "DISTRITO": "SAN SEBASTIAN",
      "NOMCCPP": "SAN SEBASTIAN",
      "CUESTIONARIO": "1",
      "CONG_T": "376660",
      "VIV": "5",
      "ACTIVIDAD": "Recuperar",
      "FECHA": "3-Ago",
      "HORAVISITA": "12:00",
      "HORADECITA": "",
      "OBSERVACIONES": "",
      "FECHA_CREACION": "23/07/2021"
    },
    {
      "COD_SEDE": "15",
      "NOM_SEDE": "LIMA",
      "NOM_USUARIO": "COAQUIRA PINEDA, SILVIA",
      "CARGO": "ENCUESTADORA",
      "PERIODO": "1",
      "DISTRITO": "SAN SEBASTIAN",
      "NOMCCPP": "SAN SEBASTIAN",
      "CUESTIONARIO": "1",
      "CONG_T": "376660",
      "VIV": "6",
      "ACTIVIDAD": "Encuestar",
      "FECHA": "3-Ago",
      "HORAVISITA": "13:00",
      "HORADECITA": "",
      "OBSERVACIONES": "",
      "FECHA_CREACION": "23/07/2021"
    },
    {
      "COD_SEDE": "15",
      "NOM_SEDE": "LIMA",
      "NOM_USUARIO": "COAQUIRA PINEDA, SILVIA",
      "CARGO": "ENCUESTADORA",
      "PERIODO": "1",
      "DISTRITO": "SAN SEBASTIAN",
      "NOMCCPP": "SAN SEBASTIAN",
      "CUESTIONARIO": "1",
      "CONG_T": "376660",
      "VIV": "7",
      "ACTIVIDAD": "Encuestar",
      "FECHA": "3-Ago",
      "HORAVISITA": "14:00",
      "HORADECITA": "",
      "OBSERVACIONES": "",
      "FECHA_CREACION": "23/07/2021"
    },
    {
      "COD_SEDE": "15",
      "NOM_SEDE": "LIMA",
      "NOM_USUARIO": "COAQUIRA PINEDA, SILVIA",
      "CARGO": "ENCUESTADORA",
      "PERIODO": "1",
      "DISTRITO": "SAN SEBASTIAN",
      "NOMCCPP": "SAN SEBASTIAN",
      "CUESTIONARIO": "1",
      "CONG_T": "376660",
      "VIV": "8",
      "ACTIVIDAD": "Supervisar",
      "FECHA": "3-Ago",
      "HORAVISITA": "15:00",
      "HORADECITA": "",
      "OBSERVACIONES": "",
      "FECHA_CREACION": "23/07/2021"
    },
    {
      "COD_SEDE": "15",
      "NOM_SEDE": "LIMA",
      "NOM_USUARIO": "COAQUIRA PINEDA, SILVIA",
      "CARGO": "ENCUESTADORA",
      "PERIODO": "1",
      "DISTRITO": "SAN SEBASTIAN",
      "NOMCCPP": "SAN SEBASTIAN",
      "CUESTIONARIO": "1",
      "CONG_T": "376660",
      "VIV": "9",
      "ACTIVIDAD": "Recuperar",
      "FECHA": "3-Ago",
      "HORAVISITA": "16:00",
      "HORADECITA": "",
      "OBSERVACIONES": "",
      "FECHA_CREACION": "23/07/2021"
    }
  ]
}
